# new {#new}

* Ralston, J., Nugent, R. Toward a broader response to cardiometabolic disease. Nat Med (2019) doi:10.1038/s41591-019-0642-9.

* Bedford, J., Farrar, J., Ihekweazu, C. et al. A new twenty-first century science for effective epidemic response. Nature 575, 130–136 (2019) doi:10.1038/s41586-019-1717-y

* Shibadas Biswal, M.D., Humberto Reynales, M.D., Ph.D., Xavier Saez-Llorens, M.D., Pio Lopez, M.D., Charissa Borja-Tabora, M.D., Pope Kosalaraksa, M.D., Chukiat Sirivichayakul, M.D., Veerachai Watanaveeradej, M.D., Luis Rivera, M.D., Felix Espinoza, M.D., LakKumar Fernando, M.D., Reynaldo Dietze, M.D., et al., for the TIDES Study Group (2019) Efficacy of a Tetravalent Dengue Vaccine in Healthy Children and Adolescents. NEJM; November 6, 2019. DOI: 10.1056/NEJMoa1903869.

*  AUSTIN FRAKT (2019) JAMA Forum: Making Health Care More Productive. https://newsatjama.jama.com/2019/11/07/jama-forum-making-health-care-more-productive/

* Careful and Kind Care Requires Unhurried Conversations. https://catalyst.nejm.org/kind-care-requires-unhurried-conversations/

* Pay for Relationship: A Novel Solution to the Primary Care Crisis. https://catalyst.nejm.org/a-novel-solution-to-the-primary-care-crisis/

* Deep Medicine. https://twitter.com/JDaleMD/status/1192120913363255296

* From 1869-2019, the #Nature150 anniversary issue. https://twitter.com/EricTopol/status/1192142643309903872

* A comprehensive review of the important sex differences in cardiometabolic diseases. https://www.nature.com/articles/s41591-019-0643-8

* The use of #probiotics in hospitals is increasing. Now the first proof via genomic sequencing that these pills can induce sepsis. https://www.nature.com/articles/s41591-019-0626-9

* Now we know that tumor cells are like bacteria: they evade treatment with adaptive mutability. https://science.sciencemag.org/content/early/2019/11/06/science.aav4474

